### ISSUE TITLE
Support `generate_work`, add functions to get block hash without actually sending a transaction

### ISSUE THREAD

**Issue by stjet** [jetstream0/bananopie#4]
Adding functions to get block hash without actually sending the transaction will allow people to use locally generated work or `generate_work` RPC call easier.

**Comment by elementalennui-dev** [comment]
I second this - I'm finding out I need the block hash to create a separate call to generate the work via another server.

**Comment by stjet** [comment]
I'm thinking of making the `work` param optionally a function, and if it is a function, then passing the block hash to it as a param.

**Comment by stjet** [comment]
Since it seems like you need this, I'll get to work (hahahahahahahahhahahaha) on this ASAP

**Comment by stjet** [comment]
> I second this - I'm finding out I need the block hash to create a separate call to generate the work via another server.

In version 0.1.4 a7cc2a9, you can now pass a function (that takes block hash as parameter) instead of a string for the `work` parameter. I briefly tested but let me know if it doesn't work. @elementalennui-dev
