### ISSUE TITLE
Callable work needs to use "previous" block hash

### ISSUE THREAD

**Issue by elementalennui-dev** [jetstream0/bananopie#5]
Thanks for the quick update! I have a version working on a local fork, which led me to identify a bug.

In the send_process() function in Wallet.py

```python
#if opening block, there is no previous, so use public key as hash instead
if block["previous"] == "0000000000000000000000000000000000000000000000000000000000000000":
  block["work"] = gen_work(self.get_public_key())
else:
  block["work"] = gen_work(block["previous"])
```

we see that we use the previous hash to generate work.

In the recent update https://github.com/stjet/bananopie/commit/a7cc2a931fc01b54db67525fdd8676b160e9c36d, you use the block_hash as the input to the callable function. This fails with Block work is insufficient.

The fix would be to use the "previous" block hash as the input to the function. I tested this out in my local fork:

```python
if work:
  if callable(work):
    work = work(previous)
  block["work"] = work
```

I think it is still worth checking this condition though: if opening block, there is no previous, so use public key as hash instead...

**Comment by stjet** [comment]
That's silly of me, thanks for reporting

**Comment by elementalennui-dev** [comment]
No worries, thanks so much for getting this custom option in so quickly! Adds good flexibility around work generation within the library IMO. Appreciate the development

**Comment by stjet** [comment]
Does v0.1.4.1 fix this ([172d975](https://github.com/stjet/bananopie/commit/172d975e7acd869909bec8dc917d2189eda89867))?
Edit: wrong commit hash, sorry a bit tired

**Comment by elementalennui-dev** [comment]
It's working on my end! 🚀🍌 Thanks again!

**Comment by stjet** [comment]
Nice!
